site_name: OPIL
site_url: https://opil-documentation.readthedocs.org
repo_url: https://github.com/opil/documentation.git
site_description: OPIL Documentation
site_author: OPIL Team
docs_dir: docs
site_dir: html

markdown_extensions:
    - toc:
        baselevel: 3
        toc_depth: 4-4
    - fenced_code

use_directory_urls: false

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django
        - bash
        - yml
nav:
    - Home: index.md
    - Getting Started: 
        - Introduction to OPIL architecture: start/index.md
        - Deployment: start/deployment.md
    - Showcases:
        - Introduction: showcases/index.md 
        - Chemi: showcases/chemi.md
        - Engino: showcases/engino.md
        - Muraplast: showcases/muraplast.md
    - Administrator's Guide: 
        - OPIL Networking: admin/OPIL/opil_networking.md
        - OPIL Server: admin/OPIL/opil_server.md
        - Task Planner: 
            - Task Planner Description: admin/TP/opil_desc_tp_intro.md
            - Installation, Configuration and Upgrades: admin/TP/opil_server_tp_install.md
        - Human Machine Interface:
            - Human Machine Interface Description: admin/HMI/opil_desc_HMI_intro.md
            - Installation, Configuration and Upgrades: admin/HMI/opil_server_hmi_install.md
        - Sensing and Perception - Central SP:
            - Central Sensing & Perception Description: admin/SP/opil_desc_SP_intro.md  
            - Installation, Configuration and Upgrades: admin/SP/opil_server_sp_install.md
        - Sensing and Perception - Local SP:
            - Local Sensing & Perception Description: admin/SP/opil_desc_local_SP_intro.md
            - Installation, Configuration and Upgrades: admin/SP/opil_local_sp_install.md                   
        - RAN: 
            - RAN Description: admin/RAN/opil_desc_ran.md
            - Installation, Configuration and Upgrades: admin/RAN/opil_server_ran_install.md
        - SAN: 
            - SAN Description: admin/SAN/opil_desc_san.md
            - Installation, Configuration and Upgrades: admin/SAN/opil_server_san_install.md
        - RAN VC: 
            - VC RAN Description: admin/RANVC/opil_desc_vc_ran.md
            - Installation, Configuration and Upgrades: admin/RANVC/opil_server_ranvc_install.md           
    - Developer's Guide and API:
        - Task Planner:
            - Introduction to API: develop/TP/opil_tp_API_intro.md
            - Business Process Optimization:  develop/TP/opil_config_tp_bpo.md
            - Motion Path Planning: develop/TP/opil_config_tp_mpp.md
            - Task Supervisor: develop/TP/opil_config_tp_tasksupervisor.md
            - API: develop/TP/opil_tp_api.md
            - Interfaces: develop/TP/opil_tp_interfaces.md
        - Human Machine Interface: 
            - API: develop/HMI/opil_api_hmi.md
            - Interfaces: develop/HMI/opil_interfaces_hmi.md
        - Sensing & Perception - Central SP: 
            - API: develop/SP/opil_api_sp.md
            - Interfaces: develop/SP/opil_sp_interfaces.md
        - Sensing & Perception - Local SP: 
            - API: develop/SP/opil_api_local_sp.md
            - Interfaces: develop/SP/opil_local_sp_interfaces.md
        - Robot Agent Node (RAN): 
            - API: develop/RAN/opil_api_ran.md
            - Interfaces: develop/RAN/opil_interfaces_ran.md
            - Introduction: develop/RAN/opil_introd_ran.md
        - Sensor Agent Node (SAN): 
            - API: develop/SAN/opil_api_san.md
            - Drivers: develop/SAN/opil_drivers_san.md
            - Configuration File: develop/SAN/opil_run_san.md
        - Examples: develop/examples.md
